"""Подготавливает небольшой пакет разметки CVAT из сгенерированных масок псевдометок."""
from __future__ import annotations

import argparse
import csv
import json
import random
import zipfile
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from PIL import Image

from src.core.paths import PATHS, PROJECT_ROOT, to_project_relative_str

DEFAULT_MANIFEST_PATH = (
    PATHS.processed_data / "nucleus_segmentation" / "pseudo_labels" / "manifest.csv"
)
DEFAULT_OUTPUT_DIR = PATHS.processed_data / "nucleus_segmentation" / "cvat_batches"
LABELS = [{"name": "nucleus", "color": "#dc1e1e", "attributes": []}]
LABELMAP = "\n".join(
    [
        "# label : color_rgb : parts : actions",
        "background:0,0,0::",
        "nucleus:220,30,30::",
        "",
    ]
)


@dataclass(frozen=True)
class CvatBatchRow:
    """Одна строка манифеста, выбранная для пакета CVAT."""
    image_id: str
    image_path: Path
    pseudo_mask_path: Path
    overlay_path: Path | None
    split: str

    @classmethod
    def from_manifest_row(cls, row: dict[str, str]) -> "CvatBatchRow":
        """Создает строку из манифеста псевдометок."""
        overlay_value = row.get("overlay_path", "")
        return cls(
            image_id=row["image_id"],
            image_path=_project_path(row["image_path"]),
            pseudo_mask_path=_project_path(row["pseudo_mask_path"]),
            overlay_path=_project_path(overlay_value) if overlay_value else None,
            split=row.get("split", "unsplit"),
        )


def parse_args() -> argparse.Namespace:
    """Разбирает аргументы командной строки."""

    parser = argparse.ArgumentParser(
        description="Prepare image and preannotation ZIP files for a CVAT task."
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST_PATH,
        help="Pseudo-label manifest.csv generated by scripts/export_pseudo_masks.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory where CVAT batch files will be written.",
    )
    parser.add_argument(
        "--batch-name",
        default="batch_001",
        help="Name of the CVAT batch output directory.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=200,
        help="Number of images to include in the batch.",
    )
    parser.add_argument(
        "--split",
        default="train",
        help="Split to sample from. Use 'all' to sample across all splits.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for deterministic sampling.",
    )
    return parser.parse_args()


def _project_path(path_value: str) -> Path:
    """Разрешает значение пути относительно проекта."""
    path = Path(path_value)
    if path.is_absolute():
        return path
    return PROJECT_ROOT / path


def load_manifest_rows(manifest_path: Path, split: str = "train") -> list[CvatBatchRow]:
    """Загружает строки манифеста псевдометок для разбиения."""
    if not manifest_path.is_file():
        raise FileNotFoundError(f"Manifest does not exist: {manifest_path}")

    rows: list[CvatBatchRow] = []
    with manifest_path.open(newline="", encoding="utf-8") as file:
        reader = csv.DictReader(file)
        for row in reader:
            if split != "all" and row.get("split") != split:
                continue
            batch_row = CvatBatchRow.from_manifest_row(row)
            if not batch_row.image_path.is_file():
                raise FileNotFoundError(f"Image file does not exist: {batch_row.image_path}")
            if not batch_row.pseudo_mask_path.is_file():
                raise FileNotFoundError(
                    f"Pseudo-mask file does not exist: {batch_row.pseudo_mask_path}"
                )
            rows.append(batch_row)

    if not rows:
        raise ValueError(f"No manifest rows found for split: {split}")
    return rows


def sample_rows(rows: list[CvatBatchRow], limit: int, seed: int) -> list[CvatBatchRow]:
    """Возвращает детерминированно выбранное подмножество."""
    if limit <= 0:
        raise ValueError(f"limit must be positive, got {limit}")
    rng = random.Random(seed)
    selected_rows = rows.copy()
    rng.shuffle(selected_rows)
    return sorted(selected_rows[: min(limit, len(selected_rows))], key=lambda row: row.image_id)


def _write_batch_manifest(rows: list[CvatBatchRow], path: Path) -> None:
    """Записывает манифест уровня пакета для трассируемости."""
    fieldnames = [
        "image_id",
        "image_path",
        "pseudo_mask_path",
        "overlay_path",
        "split",
    ]
    with path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(
                {
                    "image_id": row.image_id,
                    "image_path": to_project_relative_str(row.image_path),
                    "pseudo_mask_path": to_project_relative_str(row.pseudo_mask_path),
                    "overlay_path": to_project_relative_str(row.overlay_path)
                    if row.overlay_path
                    else "",
                    "split": row.split,
                }
            )


def _write_labels(path: Path) -> None:
    """Записывает JSON меток CVAT."""
    path.write_text(json.dumps(LABELS, indent=2), encoding="utf-8")


def _write_images_zip(rows: list[CvatBatchRow], path: Path) -> None:
    """Записывает исходные изображения в ZIP-архив, пригодный для загрузки в CVAT."""
    with zipfile.ZipFile(path, mode="w", compression=zipfile.ZIP_DEFLATED) as archive:
        for row in rows:
            archive.write(row.image_path, arcname=row.image_path.name)


def _write_mask_png_for_cvat(source_mask_path: Path, archive: zipfile.ZipFile, arcname: str) -> None:
    """Преобразует псевдомаску 0/255 в оттеночный PNG CVAT 0/1 внутри ZIP."""
    mask = np.asarray(Image.open(source_mask_path).convert("L"))
    cvat_mask = (mask > 0).astype(np.uint8)
    with archive.open(arcname, mode="w") as file:
        Image.fromarray(cvat_mask).save(file, format="PNG")


def _write_preannotations_zip(rows: list[CvatBatchRow], path: Path) -> None:
    """Записывает псевдомаски в формате импорта CVAT Segmentation Mask."""
    with zipfile.ZipFile(path, mode="w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("labelmap.txt", LABELMAP)
        archive.writestr(
            "ImageSets/Segmentation/default.txt",
            "\n".join(row.image_id for row in rows) + "\n",
        )
        for row in rows:
            mask_name = f"{row.image_id}.png"
            _write_mask_png_for_cvat(
                row.pseudo_mask_path,
                archive,
                arcname=f"SegmentationClass/{mask_name}",
            )
            _write_mask_png_for_cvat(
                row.pseudo_mask_path,
                archive,
                arcname=f"SegmentationObject/{mask_name}",
            )


def prepare_cvat_batch(
    rows: list[CvatBatchRow],
    output_dir: Path,
    batch_name: str,
) -> Path:
    """Подготавливает все артефакты пакета CVAT и возвращает каталог пакета."""
    batch_dir = output_dir / batch_name
    batch_dir.mkdir(parents=True, exist_ok=True)
    _write_batch_manifest(rows, batch_dir / "manifest.csv")
    _write_labels(batch_dir / "labels.json")
    _write_images_zip(rows, batch_dir / "images.zip")
    _write_preannotations_zip(rows, batch_dir / "preannotations_segmentation_mask.zip")
    return batch_dir


def main() -> None:
    """Точка входа CLI."""

    args = parse_args()
    rows = load_manifest_rows(args.manifest, split=args.split)
    selected_rows = sample_rows(rows, limit=args.limit, seed=args.seed)
    batch_dir = prepare_cvat_batch(
        rows=selected_rows,
        output_dir=args.output_dir,
        batch_name=args.batch_name,
    )
    print(f"Prepared CVAT batch: {to_project_relative_str(batch_dir)}")
    print(f"Images: {len(selected_rows)}")
    print(f"Images ZIP: {to_project_relative_str(batch_dir / 'images.zip')}")
    print(
        "Preannotations ZIP: "
        f"{to_project_relative_str(batch_dir / 'preannotations_segmentation_mask.zip')}"
    )
    print(f"Labels: {to_project_relative_str(batch_dir / 'labels.json')}")


if __name__ == "__main__":
    main()
